language: generic
sudo: enabled
dist: trusty
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y git-core curl jq unzip vboot-kernel-utils binutils kpartx
script: ./build.sh
deploy:
  provider: releases
  api_key: GITHUB_API_KEY
  skip_cleanup: true
  file: "slack.tgz"
  on:
    tags: true
